#pragma once
#include"Lenz/Core.h"
#include"Lenz/App.h"
#include"Lenz/Layer.h"
#include"Lenz/Renderer/Renderer.h"
#include"Lenz/Renderer/Buffer.h"
#include"Lenz/Inputs.h"
#include"Lenz/InputCodes.h"
#include"Lenz/Renderer/Defines.h"
#include"Lenz/Renderer/Uniform.h"
#include"Lenz/Scene/Scene.h"
#include"Lenz/Scene/Physics.h"
#include"Lenz/Renderer/Text.h"
#include"Lenz/Scene/Physics.h"

#include"Lenz/EntryPoint.h"